### ISSUE TITLE
Compile error on linux

### ISSUE THREAD

**Issue by lemuellew** [n-o-o-n/idp_hexagon#1]
Ubuntu 20.04.1 LTS
gcc version 9.3.0
GNU Make 4.2.1

`make[2]: Entering directory '/home/ubuntu/Workspace/idasdk72/module/hexagon'
g++ -m64 --shared -Wl,--no-undefined -o ../../bin/procs/hexagon.so obj/x64_linux_gcc_32/ana.o obj/x64_linux_gcc_32/emu.o obj/x64_linux_gcc_32/ins.o obj/x64_linux_gcc_32/out.o obj/x64_linux_gcc_32/reg.o obj/x64_linux_gcc_32/loader.o -L../../lib/x64_linux_gcc_32/ -lida -Wl,--build-id -Wl,--gc-sections -Wl,--warn-shared-textrel -Wl,-O1 -Wl,-Map,obj/x64_linux_gcc_32/hexagon.so.map -Wl,--version-script=../../module/exports.def -lrt -lpthread -lc
/usr/bin/ld: obj/x64_linux_gcc_32/emu.o: in function `jump_pattern_t::jump_pattern_t(switch_info_t*, char const (*) [4], int)':
/home/ubuntu/Workspace/idasdk72/module/hexagon/../../include/jumptable.hpp:517: undefined reference to `hex_jump_pattern_t::s_depends'
collect2: error: ld returned 1 exit status
make[2]: *** [../../module.mak:49: ../../bin/procs/hexagon.so] Error 1
make[2]: Leaving directory '/home/ubuntu/Workspace/idasdk72/module/hexagon'
make[1]: *** [makefile:57: hexagon] Error 2
make[1]: Leaving directory '/home/ubuntu/Workspace/idasdk72/module'
make: *** [makefile:26: module] Error 2`

**Comment by bkerler** [comment]
Please see PR  #2 for a fix. Cheers.

**Comment by n-o-o-n** [comment]
Fixed.
