### ISSUE TITLE
An idea for duplex handling

### ISSUE THREAD

**Issue by flowswitch** [n-o-o-n/idp_hexagon#10]
A duplex can be reported to IDA as two separate insns: 
- report the first half as an insn of size 2
- ana() will be called at ea misaligned by 2 for the second half
- check for such misaligns && for the aligned word being a duplex, decode the second half (from a full aligned word) and report it as another insn of size 2
Opcode bytes display would be mixed up of course (as the duplex encoding is not split nicely as 16:16), but we'd get two separate insns, each with it's own ops etc, creating instruc_t table would be possible too (no more need to represent each possible duplex combination as a separate insn).

**Comment by n-o-o-n** [comment]
True, this would greatly simplify the instruction flow analysis, but there's a catch.
As I wrote in emu.cpp:
_Ideally the duplex instructions should be represented as two individual insn_t. But this would conflict with the way how IDA associates instructions with physical addresses (EAs), because in duplex instructions the logically "first" sub-instruction is at a higher address._
So instead of current view:
```
LOAD:0001B4B4 25 17 21 11                 { r1 = memub(r2 + #1)
LOAD:0001B4B4                               r5 = memub(r2 + #7) }
```
you would get something like this:
```
LOAD:0001B4B4 25 17                       { r5 = memub(r2 + #7)
LOAD:0001B4B6 21 11                         r1 = memub(r2 + #1) }
```
And the resulting output wouldn't match the native tools' output. Do you want this?

**Comment by flowswitch** [comment]
Actually, nothing prevents you from doing like this:
```
LOAD:0001B4B4 25 17                 { r1 = memub(r2 + #1)
LOAD:0001B4B6 21 11                   r5 = memub(r2 + #7) }
```
- decode the high half when ana() is called first time
- decode the low half at (ea & ~2) when ana() is called with (ea & 3)==2 (checking that it's a duplex, not user pressing C at misaligned ea)

You'll need to inspect a full aligned dword in both cases anyway (to extract parse and iclass), so it is just a matter of which bits you are decoding first.
Opcode bytes display wouldn't match the insn of course, byte patching would modify the "other" insn, but is it so important? We all know where to look in such cases.

**Comment by n-o-o-n** [comment]
I'll try that approach (time permitting).

**Comment by n-o-o-n** [comment]
BTW, with constant extenders it's gonna look like this:
```
LOAD:0003923C C1 65 08 03 92 2D                         r3 = ##0x3089705F
LOAD:00039242 F3 29                                     r2 = add(sp, #0x64) }
```

**Comment by flowswitch** [comment]
Personally I don't care about opcodes of this arch 99.9% of time. Before discovering your complete project I was experimenting with even more "heretic" approach - on a first ana() call parse entire packet to an insn_t[4] cache array, reorder the results to move jumps and new value consumers to the end of packet, feed them in this order to subsequent ana()s targeting the same packet. But other users can have different requirements of course.

**Comment by n-o-o-n** [comment]
Please check the latest commit.
