### ISSUE TITLE
Just a question, not a "real" issue

### ISSUE THREAD

**Issue by hustc12** [n-o-o-n/idp_hexagon#17]
hi,
Recently I've been looking for info about Hexagon HMX. It looks like there is rare info for this extension. Thank you for your repo and I am wondering where did you find those HMX instructions?

**Comment by Rot127** [comment]
Hi! Dev of [Rizin's](https://rizin.re/) Hexagon plugin here.
There is currently no public source for the HMX definitions. I am not even aware of any leaks. @n-o-o-n probably has them from somewhere else.

Naturally I would be very interested in them as well.

**Comment by n-o-o-n** [comment]
You are correct in assuming that information about HMX extension is not public and probably will never be.
QCOM wants people to use their libraries (QNN/SNPE) rather than providing direct access. Their argument is that it allows them to change any aspect of it without worrying about compatibility.

I gathered info primarilty from Hexagon SDK.
For example, Hexagon_SDK/x.y.z.w/tools/HEXAGON_Tools/a.b.cd/Tools/target/hexagon/include/hmx_hexagon_protos.h contains quite a long list of HMX intrinsics.
The tools binaries contain instruction decoding tables that are compiled from .td files (see for example https://github.com/llvm/llvm-project/blob/main/llvm/lib/Target/Hexagon/HexagonDepInstrInfo.td).

But probably the most complete information could be obtained from the instruction simulator (hexagon-sim).
```
@hexagon-sim --pmu_statsfile $(TARGET_DIR)/pmu.log \
            --archstring "--QDSP6_MX_PRESENT 1 --hmxdebuglvl 5 --hmxdebugfile hmx.log" \
            --mv69 --mhmx -- $(TARGET) $(ARG)
```

**Comment by Rot127** [comment]
Ah yes. For Rizin I've been too lazy yet to go down the "extract from SDK" root. And only use the LLVM definitions.

Have you, by any chance, a script to share which parses the log file into something machine readable?

**Comment by n-o-o-n** [comment]
No, I don't have that.
I could only add that in order to test HMX in simulator, you'd have to enable it in SSR register, bit 26:
```
static void hmx_enable( void )
{
    // set bit SSR[26]: 2nd Coprocessor Enable
    asm volatile(
        "r0 = ssr\n\t"
        "r0 = setbit(r0, #26)\n\t"
        "ssr = r0\n\t"
        ::: "r0"
    );
}
```

**Comment by Rot127** [comment]
Will look into it when hopefully some spare time comes up. Thanks for the instructions!

**Comment by qian-gu** [comment]
sorry for new comments after a long time, I have checked the hmx_hexagon_protos.h file and got some questions about HMX:

1. It's weird that there are no HMX calculation intrinsic and asm in the prototype file, there are only clear, swap and load/store intrinsic actually.
2. What does "virtual register" means, it seems HMX has its own physical register file. https://github.com/n-o-o-n/idp_hexagon/blob/9b735bbec74206eb9ab53f9498dba1b2a5810355/hexagon/ins.h#L57-L62
3. There are some code snippets like `acc:2x1` and `acc:2x2`, is it reasonable to infer that HMX array is dividen into 4 sub-array in hardware?

Looking foward some reply and discuss, thanks!

**Comment by n-o-o-n** [comment]
hi @qian-gu,

First of all, I would advise to run instruction simulator as explained above - this would give you lots of information.
      
>     1. It's weird that there are no HMX calculation intrinsic and asm in the prototype file, there are only clear, swap and load/store intrinsic actually.
The thing is that MAC instruction bundle that calculates NxM convolution must contain [at least] two instructions - the loading of activation and loading of weights. The result of calculation is written in acc.

>     2. What does "virtual register" means, it seems HMX has its own physical register file.
It's not a register file. For example, the bundle
```
{ activation.hf = mxmem(r0, r1):deep
  weight.hf = mxmem(r2, r3) }
```
means "run the MAC pipeline using input pointers in r0 and r2, with tensor layouts specified in r1 and r3".

>     3. There are some code snippets like `acc:2x1` and `acc:2x2`, is it reasonable to infer that HMX array is dividen into 4 sub-array in hardware?
I've no idea.

Sorry for late answer.

**Comment by qian-gu** [comment]
Thanks for your explanation, give me a lot of inspiration.
