### ISSUE TITLE
Crash on IDA 8.3

### ISSUE THREAD

**Issue by vanhauser-thc** [n-o-o-n/idp_hexagon#18]
I compiled the processor module and copied it to IDA Pro 8.3, then loaded a QSDP6 elf binary and then:
```
Oops, IDA has almost crashed! (signum=11)
Unloading IDP module /opt/idapro-8.3/procs/hexagon64.so...
```
I know this is very little information, if you can supply me with hints how to give you the details necessary to fix it I will add this here :)

**Comment by n-o-o-n** [comment]
Unfortunately IDA procs plugins are targeted for a specific version of IDA due the rapidly changing APIs.
The latest IDA the plugin was tested with was version 7.7.
Sorry, I don't have any newer version at the moment.
