### ISSUE TITLE
System instructions

### ISSUE THREAD

**Issue by Rot127** [n-o-o-n/idp_hexagon#19]
Qualcomm added some system instructions in November (and before).
See: https://github.com/llvm/llvm-project/commits/bd91cf8d83a9c352a02ea1b66095ef53362e027c

They should be added (if not already done).

**Comment by Rot127** [comment]
https://github.com/n-o-o-n/idp_hexagon/releases/tag/v5.3

**Comment by n-o-o-n** [comment]
Actually, all of those system instructions were supported by idp_hexagon a long time ago.
QCOM is just reluctant to publish them.

**Comment by Rot127** [comment]
Sorry, I did not tested them back then. Just wanted to point towards the new commits.
