### ISSUE TITLE
IDA crash...

### ISSUE THREAD

**Issue by ovexler** [n-o-o-n/idp_hexagon#5]
I have tried to use the windows  pre compiled - hexagon-ida75-v3.0.7z - version.
After loading Elf or even binary file ... IDA Segment View crashes ...
Any idea ?
I am using - IDA Version 7.5.201028 Windows x64 (32-bit address size)

**Comment by flowswitch** [comment]
That's due to DS=CS=-1 set in LPH (why??). See https://github.com/bkerler/idp_hexagon/pull/1 (a quick&dirty solution, but it works).

**Comment by n-o-o-n** [comment]
The latest commit fixes this issue.
Many thanks to @flowswitch.
