### ISSUE TITLE
LPH.flags PR_ALIGN should be cleared

### ISSUE THREAD

**Issue by flowswitch** [n-o-o-n/idp_hexagon#6]
Although the core doesn't support unaligned mem accesses, there are many binaries containing "packed" unaligned 32-bit values (accessed as _val = ptr[0] | (ptr[1]<<8) | (ptr[2]<<16) | (ptr[3]<<24)_). PR_ALIGN flag prohibits converting such values to dwords/offsets. It looks safe to remove PR_ALIGN, code alignment is enforced in ana() already.

**Comment by n-o-o-n** [comment]
The latest commit fixes this issue.
