### ISSUE TITLE
Missing system registers s64-s80

### ISSUE THREAD

**Issue by Rot127** [n-o-o-n/idp_hexagon#8]
The indices assigned to the system registers differ from the programmers reference manual.

For example:
`pmucfg` is `s53` in the manual but in https://github.com/n-o-o-n/idp_hexagon/blob/5165ff29960331a9296f0cbddcd7c13606623fb3/hexagon/out.cpp#L80 it is `s58`.

Also:
Some registers are not present at all or have different names:
In the manual `s22` is register `IAD`, https://github.com/n-o-o-n/idp_hexagon/blob/5165ff29960331a9296f0cbddcd7c13606623fb3/hexagon/out.cpp#L80 the line above calls it `vid1`.

**Comment by Rot127** [comment]
Just recognized that you probably used the SDK to build and decompile the instructions with all system registers.
Anyway. There are some registers missing (> s64). Here is a list with additional registers:
<details>

>   ```python
>   regs = [
>     "sgp0",       # s0  
>     "sgp1",       # s1
>     "stid",       # s2
>     "elr",        # s3
>     "badva0",     # s4
>     "badva1",     # s5
>     "ssr",        # s6
>     "ccr",        # s7
>     "htid",       # s8
>     "badva",      # s9
>     "imask",      # s10
>     "gevb",       # s11
>     "s12",        # s12
>     "s13",        # s13
>     "s14",        # s14
>     "s15",        # s15
>     "evb",        # s16
>     "modectl",    # s17
>     "syscfg",     # s18
>     "s19",        # s19
>     "ipendad",    # s20
>     "vid",        # s21
>     "vid1",       # s22
>     "bestwait",   # s23
>     "s24",        # s24
>     "schedcfg",   # s25
>     "s26",        # s26
>     "cfgbase",    # s27
>     "diag",       # s28
>     "rev",        # s29
>     "pcyclelo",   # s30
>     "pcyclehi",   # s31
>     "isdbst",     # s32
>     "isdbcfg0",   # s33
>     "isdbcfg1",   # s34
>     "livelock",   # s35
>     "brkptpc0",   # s36
>     "brkptcfg0",  # s37
>     "brkptpc1",   # s38
>     "brkptcfg1",  # s39
>     "isdbmbxin",  # s40
>     "isdbmbxout", # s41
>     "isdben",     # s42
>     "isdbgpr",    # s43
>     "pmucnt4",    # s44
>     "pmucnt5",    # s45
>     "pmucnt6",    # s46
>     "pmucnt7",    # s47
>     "pmucnt0",    # s48
>     "pmucnt1",    # s49
>     "pmucnt2",    # s50
>     "pmucnt3",    # s51
>     "pmuevtcfg",  # s52
>     "s53",        # s53
>     "pmuevtcfg1", # s54
>     "pmustid1",   # s55
>     "timerlo",    # s56
>     "timerhi",    # s57
>     "s58",        # s58
>     "s59",        # s59
>     "s60",        # s60
>     "s61",        # s61
>     "s62",        # s62
>     "s63",        # s63
>     "commit1t",   # s64
>     "commit2t",   # s65
>     "commit3t",   # s66
>     "commit4t",   # s67
>     "commit5t",   # s68
>     "commit6t",   # s69
>     "pcycle1t",   # s70
>     "pcycle2t",   # s71
>     "pcycle3t",   # s72
>     "pcycle4t",   # s73
>     "pcycle5t",   # s74
>     "pcycle6t",   # s75
>     "stfinst",    # s76
>     "isdbcmd",    # s77
>     "isdbver",    # s78
>     "brkptinfo",  # s79
>     "rgdr3"       # s80
>   ]
>   ``` 

</details>

Unfortunately I don't use IDA so won't be able to create a pull request for it.

**Comment by n-o-o-n** [comment]
Thanks for reporting this issue. It has been fixed in the latest commit.
I should add that although QCOM tries to makes registers compatible between versions, sometimes they change names or positions. For example, the IAD that you mentioned, was indeed S22 in v60/v61, but now it's a field inside IPENDAD (S20).
