### ISSUE TITLE
instruction memw ‘s data reference missed

### ISSUE THREAD

**Issue by hyperchem** [n-o-o-n/idp_hexagon#9]
when the loader comes to dissamble the following instruction, the data reference of imm32 (unk_B01E19EC) is missed. Would you have a look at this? 
`r0 = memw(##unk_B01E19EC) }`

**Comment by hyperchem** [comment]
one more bug,  struct member can not be applied to code like this `{ r2 = memw(r2 + #0x1C) }`, in which 0x1C is supposed to an offset to a structure.

**Comment by n-o-o-n** [comment]
Please open the attached file [u.o.zip](https://github.com/n-o-o-n/idp_hexagon/files/7522142/u.o.zip) in IDA, create a structure, then press 'T' (Offset (struct)...), and voila.

If your instruction is more complicated and has more than two operands, then yes, this might be a problem (please see [Issues](https://github.com/n-o-o-n/idp_hexagon#issues) on the main page).

**Comment by n-o-o-n** [comment]
> 
> 
> when the loader comes to dissamble the following instruction, the data reference of imm32 (unk_B01E19EC) is missed. Would you have a look at this? `r0 = memw(##unk_B01E19EC) }`

This just means that memory at this address is either not visible to IDA (for example, it refers to another module or a HW block) or simply the memory is still unexplored.
